# Generated by Django 4.0.4 on 2022-04-29 14:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
