# Generated by Django 4.0.4 on 2022-04-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_bike_no_of_owner_alter_bike_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
